export const EMOTES: { name: string; new?: boolean; tier: 'follower' | '1' | '2' | '3'; updated?: boolean; url: string }[] = [
  {
    name: 'bamboe1Butter',
    tier: '1',
    url: '/emotes/bamboe1Butter.png',
  },
  {
    name: 'bamboe1Cool',
    tier: '1',
    url: '/emotes/bamboe1Cool.png',
  },
  {
    name: 'bamboe1Cozy',
    tier: '1',
    url: '/emotes/bamboe1Cozy.png',
  },
  {
    name: 'bamboe1Dead',
    tier: '1',
    updated: true,
    url: '/emotes/bamboe1Dead.png',
  },
  {
    name: 'bamboe1Derp',
    tier: '1',
    url: '/emotes/bamboe1Derp.png',
  },
  {
    name: 'bamboe1KEKW',
    tier: 'follower',
    url: '/emotes/bamboe1KEKW.png',
  },
  {
    name: 'bamboe1Love',
    tier: 'follower',
    url: '/emotes/bamboe1Love.png',
  },
  {
    name: 'bamboe1Lurk',
    tier: '1',
    url: '/emotes/bamboe1Lurk.gif',
  },
  {
    name: 'bamboe1Rage',
    tier: 'follower',
    url: '/emotes/bamboe1Rage.png',
  },
  {
    name: 'bamboe1Raid',
    tier: '1',
    url: '/emotes/bamboe1Raid.gif',
  },
  {
    name: 'bamboe1Sad',
    tier: 'follower',
    url: '/emotes/bamboe1Sad.png',
  },
  {
    name: 'bamboe1Scared',
    tier: 'follower',
    url: '/emotes/bamboe1Scared.png',
  },
  {
    name: 'bamboe1Sexy',
    tier: '1',
    url: '/emotes/bamboe1Sexy.png',
  },
  {
    name: 'bamboe1Snom',
    tier: '3',
    url: '/emotes/bamboe1Snom.png',
  },
  {
    name: 'bamboe1Bla',
    new: true,
    tier: '1',
    url: '/emotes/bamboe1Bla.gif',
  },
  {
    name: 'bamboe1Bonk',
    new: true,
    tier: '1',
    url: '/emotes/bamboe1Bonk.png',
  },
  {
    name: 'bamboe1Clap',
    new: true,
    tier: '1',
    url: '/emotes/bamboe1Clap.gif',
  },
  {
    name: 'bamboe1Drink',
    new: true,
    tier: '1',
    url: '/emotes/bamboe1Drink.png',
  },
  {
    name: 'bamboe1GG',
    new: true,
    tier: '1',
    url: '/emotes/bamboe1GG.png',
  },
  {
    name: 'bamboe1Innocent',
    new: true,
    tier: '1',
    url: '/emotes/bamboe1Innocent.gif',
  },
  {
    name: 'bamboe1Noted',
    new: true,
    tier: '1',
    url: '/emotes/bamboe1Noted.gif',
  },
  {
    name: 'bamboe1Party',
    new: true,
    tier: '1',
    url: '/emotes/bamboe1Party.gif',
  },
  {
    name: 'bamboe1Pat',
    new: true,
    tier: '1',
    url: '/emotes/bamboe1Pat.png',
  },
  {
    name: 'bamboe1Shy',
    new: true,
    tier: '1',
    url: '/emotes/bamboe1Shy.gif',
  },
  {
    name: 'bamboe1Sleep',
    new: true,
    tier: '1',
    url: '/emotes/bamboe1Sleep.png',
  },
  {
    name: 'bamboe1Steer',
    new: true,
    tier: '1',
    url: '/emotes/bamboe1Steer.gif',
  },
];
