export const GAME_METADATA: Record<string, Partial<{ backgroundImagePath: string; color: string; iconPath: string; intermissionTextMode: string }>> = {
  'A Short Hike': {
    backgroundImagePath: '/modern/game-backgrounds/a-short-hike.jpg',
    color: 'rgba(188, 93, 32, 0.35)',
    iconPath: '/modern/programs/a-short-hike.icon.png',
    intermissionTextMode: 'default',
  },
  'Bread & Fred': {
    backgroundImagePath: '/modern/game-backgrounds/bread-and-fred.jpg',
    color: 'rgba(77, 77, 159, 0.25)',
    iconPath: '/modern/programs/bread-and-fred.icon.png',
    intermissionTextMode: 'default',
  },
  'Brotato': {
    backgroundImagePath: '/modern/game-backgrounds/brotato.jpg',
    color: 'transparent',
    iconPath: '/modern/programs/brotato.icon.png',
    intermissionTextMode: 'default',
  },
  'Cities: Skylines II': {
    backgroundImagePath: '/modern/game-backgrounds/cities-skylines-ii.jpg',
    color: 'rgba(30, 71, 159, 0.5)',
    iconPath: '/modern/programs/cities-skylines-ii.icon.png',
    intermissionTextMode: 'default',
  },
  'Cult of the Lamb': {
    backgroundImagePath: '/modern/game-backgrounds/cult-of-the-lamb.jpg',
    color: 'rgba(239, 17, 30, 0.35)',
    iconPath: '/modern/programs/cult-of-the-lamb.icon.png',
    intermissionTextMode: 'default',
  },
  'Deep Rock Galactic: Survivor': {
    backgroundImagePath: '/modern/game-backgrounds/drg-survivor.jpg',
    color: 'transparent',
    iconPath: '/modern/programs/drg-survivor.icon.png',
    intermissionTextMode: 'default',
  },
  'Escape from Duckov': {
    backgroundImagePath: '/modern/game-backgrounds/escape-from-duckov.jpg',
    color: 'rgba(245, 145, 15, 0.625)',
    iconPath: '/modern/programs/escape-from-duckov.icon.png',
    intermissionTextMode: 'default',
  },
  'Golf It!': {
    backgroundImagePath: '/modern/game-backgrounds/golf-it.jpg',
    color: 'rgba(135, 80, 5, 0.5)',
    iconPath: '/modern/programs/golf-it.icon.png',
    intermissionTextMode: 'default',
  },
  'Lego & Brickbuilding': {
    backgroundImagePath: '/modern/game-backgrounds/lego-and-brickbuilding.jpg',
    color: 'rgba(170, 204, 0, 0.35)',
    iconPath: '/modern/programs/brickbuilding.icon.png',
    intermissionTextMode: 'chatting',
  },
  'Just Chatting': {
    intermissionTextMode: 'chatting',
  },
  'Mario Kart World': {
    backgroundImagePath: '/modern/game-backgrounds/mario-kart-world.jpg',
    color: 'rgba(228, 0, 15, 0.35)',
    iconPath: '/modern/programs/mario-kart-world.icon.png',
    intermissionTextMode: 'default',
  },
  'Need for Speed: Carbon': {
    backgroundImagePath: '/modern/game-backgrounds/need-for-speed-carbon.jpg',
    color: 'rgba(97, 28, 33, 0.5)',
    iconPath: '/modern/programs/need-for-speed-carbon.icon.png',
    intermissionTextMode: 'default',
  },
  'Need for Speed: Most Wanted': {
    backgroundImagePath: '/modern/game-backgrounds/need-for-speed-most-wanted.jpg',
    color: 'rgba(4, 60, 73, 0.75)',
    iconPath: '/modern/programs/need-for-speed-most-wanted.icon.png',
    intermissionTextMode: 'default',
  },
  'Pokémon Legends: Arceus': {
    backgroundImagePath: '/modern/game-backgrounds/pokemon-legends-arceus.jpg',
    color: 'rgba(225, 210, 189, 0.9)',
    iconPath: '/modern/programs/pokemon-legends-arceus.icon.png',
    intermissionTextMode: 'default',
  },
  'Pokémon Sword/Shield': {
    backgroundImagePath: '/modern/game-backgrounds/pokemon-sword.jpg',
    color: 'rgba(255, 255, 255, 0.5)',
    iconPath: '/modern/programs/pokemon-sword.icon.png',
    intermissionTextMode: 'default',
  },
  'Software and Game Development': {
    backgroundImagePath: '/modern/game-backgrounds/software-and-game-development.jpg',
    color: 'rgba(170, 204, 0, 0.5)',
    iconPath: '/modern/programs/software-and-game-development.icon.png',
    intermissionTextMode: 'default',
  },
  'TCG Card Shop Simulator': {
    backgroundImagePath: '/modern/game-backgrounds/tcg-card-shop-simulator.jpg',
    color: 'rgba(167, 14, 19, 0.35)',
    iconPath: '/modern/programs/tcg-card-shop-simulator.icon.png',
    intermissionTextMode: 'default',
  },
  'Trackmania': {
    backgroundImagePath: '/modern/game-backgrounds/trackmania.jpg',
    color: 'rgba(252, 3, 26, 0.5)',
    iconPath: '/modern/programs/trackmania.icon.png',
    intermissionTextMode: 'default',
  },
  'VEIN': {
    backgroundImagePath: '/modern/game-backgrounds/vein.jpg',
    color: 'rgba(171, 0, 0, 0.75)',
    iconPath: '/modern/programs/vein.icon.png',
    intermissionTextMode: 'default',
  },
} as const;
